name: .NET 7

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 7
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'
    - name: Install dependencies
      run: dotnet restore "Demo/Demo.sln"
    - name: Build
      run: dotnet build "Demo/Demo.sln" --configuration Release --no-restore
